require "sportradar/api/football/stat_pack"
require "sportradar/api/football/stat_pack/defense"
require "sportradar/api/football/stat_pack/extra_points"
require "sportradar/api/football/stat_pack/field_goals"
require "sportradar/api/football/stat_pack/fumbles"
require "sportradar/api/football/stat_pack/int_returns"
require "sportradar/api/football/stat_pack/kickoffs"
require "sportradar/api/football/stat_pack/kick_returns"
require "sportradar/api/football/stat_pack/misc_returns"
require "sportradar/api/football/stat_pack/passing"
require "sportradar/api/football/stat_pack/penalties"
require "sportradar/api/football/stat_pack/punt_returns"
require "sportradar/api/football/stat_pack/punts"
require "sportradar/api/football/stat_pack/receiving"
require "sportradar/api/football/stat_pack/rushing"


require "sportradar/api/football/team"
require "sportradar/api/football/venue"
require "sportradar/api/football/record"
require "sportradar/api/football/week"
require "sportradar/api/football/scoring"
require "sportradar/api/football/game_stats"
require "sportradar/api/football/game"
require "sportradar/api/football/quarter"
require "sportradar/api/football/drive"
require "sportradar/api/football/play"
require "sportradar/api/football/event"

require "sportradar/api/football/ncaafb_api"
require "sportradar/api/football/ncaafb"
require "sportradar/api/football/ncaafb/week"
require "sportradar/api/football/ncaafb/division"
require "sportradar/api/football/ncaafb/conference"
require "sportradar/api/football/ncaafb/subdivision"
require "sportradar/api/football/ncaafb/team"
require "sportradar/api/football/ncaafb/game"
require "sportradar/api/football/ncaafb/quarter"
require "sportradar/api/football/ncaafb/drive"
require "sportradar/api/football/ncaafb/play"
require "sportradar/api/football/ncaafb/player"


require "sportradar/api/football/nfl"
require "sportradar/api/football/nfl/week"
require "sportradar/api/football/nfl/hierarchy"
require "sportradar/api/football/nfl/division"
require "sportradar/api/football/nfl/conference"
require "sportradar/api/football/nfl/team"
require "sportradar/api/football/nfl/game"
require "sportradar/api/football/nfl/quarter"
require "sportradar/api/football/nfl/drive"
require "sportradar/api/football/nfl/event"
require "sportradar/api/football/nfl/play"
require "sportradar/api/football/nfl/player"


# to be deleted
# require "sportradar/api/ncaafb/season"
# require "sportradar/api/ncaafb/week"
# require "sportradar/api/ncaafb/game"
# require "sportradar/api/ncaafb/team"
# require "sportradar/api/ncaafb/player"
# require "sportradar/api/ncaafb/quarter"
# require "sportradar/api/ncaafb/drive"
# require "sportradar/api/ncaafb/play"
