# require_relative 'hockey/season'
# require_relative 'hockey/game'
require_relative 'hockey/team'
# require_relative 'hockey/record'
require_relative 'hockey/venue'
# require_relative 'hockey/broadcast'
# require_relative 'hockey/injury'
# require_relative 'hockey/plays'
# require_relative 'hockey/scoring'

require_relative 'hockey/nhl'
require_relative 'hockey/nhl/api'
require_relative 'hockey/nhl/conference'
require_relative 'hockey/nhl/division'
# require_relative 'hockey/nhl/season'
# require_relative 'hockey/nhl/series'
# require_relative 'hockey/nhl/schedule'
# require_relative 'hockey/nhl/game'
# require_relative 'hockey/nhl/team'
# require_relative 'hockey/nhl/player'
# require_relative 'hockey/nhl/quarter'

# require_relative 'hockey/ncaamh'
# require_relative 'hockey/ncaamh/season'
# require_relative 'hockey/ncaamh/schedule'
# require_relative 'hockey/ncaamh/tournament'
# require_relative 'hockey/ncaamh/round'
# require_relative 'hockey/ncaamh/bracket'
# require_relative 'hockey/ncaamh/game'
# require_relative 'hockey/ncaamh/half'
# require_relative 'hockey/ncaamh/hierarchy'
# require_relative 'hockey/ncaamh/division'
# require_relative 'hockey/ncaamh/conference'
# require_relative 'hockey/ncaamh/team'
# require_relative 'hockey/ncaamh/player'
